### ISSUE TITLE
In-built method to access image_compare and upload_bvas without bookmarks

### ISSUE THREAD

**Issue by Strongbird** [Sasquire/Idems-Sourcing-Suite#22]
I do not know of a way to access the image_compare or upload_bvas pages without referring to the original forum thread or bookmarking the pages in question. If I'm not just missing it completely, I would like an easy method to pull up the aforementioned pages that does not require additional bookmarks.

**Comment by Sasquire** [comment]
No, you are correct. There is no built in way to access these pages. Perhaps because I made the pages I became too used to the URLs and just have them ingrained in my mind.

I should definitely implement this feature. When I do, I want to create a sort of standardized page where other extensions can add their own bookmarks.

Alternatively, if I switch to a web extension, there should be a cleaner way to add quick links.

**Comment by Sasquire** [comment]
Implemented in 5dd2e20f5f8de359f68307fdca962c248b88d94a.

The link that will contain all future extensions will be https://e621.net/extensions
