### ISSUE TITLE
API Key link on e621 Extension Hub requires update

### ISSUE THREAD

**Issue by Strongbird** [Sasquire/Idems-Sourcing-Suite#28]
Affected page: https://e621.net/extensions

The API key needs to be updated from https://e621.net/user/api_key to https://e621.net/users/USER#/api_key, as the old link leads to a "not found" page.

**Comment by Sasquire** [comment]
Fixed in commit f7bb59215e53358c8fdf93e740989a111361addd.

A direct link to the API access page can no longer be maintained because of issues with e621. A user id must be known if this link were to be created. I have asked for a general URL that functions like the previous url but have been told to simply direct users to their homepage.
