### ISSUE TITLE
[Feature request] DeviantArt large view and social preview should also involve 100 JPEG quality modifications

### ISSUE THREAD

**Issue by The-Polymorphic** [Sasquire/Idems-Sourcing-Suite#31]
The sourcing suite checks the DeviantArt images' large view and social preview MD5s as those are downloaded and cached upon page load. However, the MD5 checker does not consider a simple change that users can make to the DA preview image URL that allows them to get higher-quality versions of such images if the original image were uploaded as JPEGs or PNGs with alpha transparency but isn't available for download.

The path in the direct image URL that determines size and quality for preview images is `w_<width #>,h_<height #>,q_<JPEG quality #>,strp` , located after `[...]/v1/fill` and before `/<title>_by_<username>_d<six base 36 digits>[...]`. The `<JPEG quality #>` is normally set to `70` for social previews and `75` for large view images. If the JPEG quality is set to `100`, then the quality of the image itself increases.

To give an example of this quality improvement in action, here's what each version of [this image](https://www.deviantart.com/sabi-arts/art/SixFanarts-Meme-837086178) looks like when viewed in Firefox's page info window, with the URL's quality fragment highlighted:

![Social Preview - Quality 70](https://user-images.githubusercontent.com/64727240/81282323-ffa02b80-9028-11ea-92ef-2198ad1b68f6.png)
![Social Preview - Quality 100](https://user-images.githubusercontent.com/64727240/81282331-03cc4900-9029-11ea-94d1-857571616036.png)
![Large View - Quality 75](https://user-images.githubusercontent.com/64727240/81282308-f9aa4a80-9028-11ea-902b-4f778cca018c.png)
![Large View - Quality 100](https://user-images.githubusercontent.com/64727240/81282317-fdd66800-9028-11ea-9ec5-88c9b8627b63.png)

**Comment by Sasquire** [comment]
Hello, sorry for the late reply, github didn't send me a notification of an issue opening.

This is definitely something that should be done on images that lack the full option. If there are only large and social previews, then the sourcing suite links to whatever the default url is. The problem I have is including too many urls. There were complaints that twitter had too many different urls, clogging the screen and slowing down the program.

It should be easy to make the upload button always use the definitive best url. For md5s shown on the screen, I think a good approach would be if the download quality is available, do not show any 100 JPEG qualities, otherwise show the 100 quality for the best available quality along with the default. This would provide a md5 matching e621 for files that have been sourced with the 100 quality.

I'm not able to make the change right now, but if there is an issue let me know. I'll implement it like I just described at the next time I can.

**Comment by Sasquire** [comment]
Solved in commit 8a096dd4c817aa02b839973f713448101e32851a. I just have it show all the URLs and md5s. I don't think a user is not likely to switch too quickly between images to cause problems.
